import 'package:flutter_test/flutter_test.dart';
import 'package:mesa/core/constants/catalog_config.dart';
import 'package:mesa/core/failures/catalog_failure.dart';
import 'package:mesa/data/catalog/exercise_json.dart';
import 'package:mesa/domain/models/body_part.dart';
import 'package:mesa/domain/models/equipment.dart';
import 'package:mesa/domain/models/exercise.dart';
import 'package:mesa/domain/models/load_model.dart';
import 'package:mesa/domain/models/muscle.dart';

/// One record of `assets/catalog/exercises.json`, as a pure map.
void main() {
  Map<String, dynamic> record({
    Object? id = '0025',
    Object? name = 'barbell bench press',
    Object? bodyPart = 'chest',
    Object? primaryMuscle = 'chest',
    Object? synergist = 'triceps',
    Object? secondaryMuscles = const ['triceps', 'delts'],
    Object? equipment = 'barbell',
    Object? loadModel = 'externalLoad',
  }) {
    return <String, dynamic>{
      'id': id,
      'name': name,
      'aliases': const ['supino reto'],
      'bodyPart': bodyPart,
      'primaryMuscle': primaryMuscle,
      'synergist': synergist,
      'secondaryMuscles': secondaryMuscles,
      'equipment': equipment,
      'loadModel': loadModel,
      'steps': const ['Lie on the bench.', 'Press.'],
      'thumbnailUrl': 'images/0025-abc.jpg',
      'gifUrl': 'videos/0025-abc.gif',
      'attribution': '© Gym visual — https://gymvisual.com/',
    };
  }

  test('reads a full record', () {
    final exercise = ExerciseJson.fromMap(record());

    expect(exercise.id, '0025');
    expect(exercise.name, 'barbell bench press');
    expect(exercise.aliases, ['supino reto']);
    expect(exercise.bodyPart, BodyPart.chest);
    expect(exercise.primaryMuscle, Muscle.chest);
    expect(exercise.synergist, Muscle.triceps);
    expect(exercise.secondaryMuscles, [Muscle.triceps, Muscle.delts]);
    expect(exercise.equipment, Equipment.barbell);
    expect(exercise.loadModel, LoadModel.externalLoad);
    expect(exercise.steps, hasLength(2));
    expect(exercise.source, ExerciseSource.catalogue);
  });

  test('resolves relative media paths against the pinned commit', () {
    // The asset stores paths, not URLs — baking the base in would add ~230 KB
    // to the APK and pin the host into the data (§5.1).
    final exercise = ExerciseJson.fromMap(record());

    expect(exercise.thumbnailUrl, '${CatalogConfig.mediaBaseUrl}images/0025-abc.jpg');
    expect(exercise.gifUrl, '${CatalogConfig.mediaBaseUrl}videos/0025-abc.gif');
  });

  test('accepts a record with no synergist', () {
    final exercise = ExerciseJson.fromMap(record(synergist: null));

    expect(exercise.synergist, isNull);
  });

  test('rejects an unknown muscle rather than defaulting it', () {
    // Deliberately unlike the Firestore converters, which are tolerant. The
    // asset is generated by a validating build, so an unknown value here means
    // the mapping tables got ahead of the Dart enums — and a default would ship
    // a catalogue that is quietly wrong instead of loudly broken.
    expect(
      () => ExerciseJson.fromMap(record(primaryMuscle: 'pectorals')),
      throwsA(
        isA<CatalogFailure>()
            .having((f) => f.kind, 'kind', CatalogFailureKind.unknownValue)
            .having((f) => f.detail, 'detail', contains('pectorals')),
      ),
    );
  });

  test('rejects an unknown equipment, body part or load model', () {
    for (final broken in [
      record(equipment: 'gravity boots'),
      record(bodyPart: 'tail'),
      record(loadModel: 'telekinesis'),
    ]) {
      expect(
        () => ExerciseJson.fromMap(broken),
        throwsA(isA<CatalogFailure>().having((f) => f.kind, 'kind', CatalogFailureKind.unknownValue)),
      );
    }
  });

  test('rejects an unknown secondary muscle too', () {
    expect(
      () => ExerciseJson.fromMap(record(secondaryMuscles: const ['triceps', 'gluteus profundus'])),
      throwsA(isA<CatalogFailure>().having((f) => f.detail, 'detail', contains('gluteus profundus'))),
    );
  });

  test('rejects a record with no id or no name', () {
    expect(
      () => ExerciseJson.fromMap(record(id: null)),
      throwsA(
        isA<CatalogFailure>().having((f) => f.kind, 'kind', CatalogFailureKind.assetMalformed),
      ),
    );
    expect(
      () => ExerciseJson.fromMap(record(name: '')),
      throwsA(
        isA<CatalogFailure>().having((f) => f.kind, 'kind', CatalogFailureKind.assetMalformed),
      ),
    );
  });
}
