import 'package:mesa/core/constants/catalog_config.dart';
import 'package:mesa/core/failures/catalog_failure.dart';
import 'package:mesa/domain/models/body_part.dart';
import 'package:mesa/domain/models/equipment.dart';
import 'package:mesa/domain/models/exercise.dart';
import 'package:mesa/domain/models/load_model.dart';
import 'package:mesa/domain/models/muscle.dart';

/// Reads one record of `assets/catalog/exercises.json` into an [Exercise].
///
/// Kept out of the loader so it can be tested as a pure function over maps,
/// with no asset bundle in sight (§11) — the same split as
/// `UserProfileConverter`.
///
/// **Strict, unlike the Firestore converters.** Those are tolerant because a
/// profile that fails to parse would lock the user out of their own app. This
/// one is the opposite case: the asset is generated by a validating build and
/// committed, so an unknown value here means the mapping tables got ahead of
/// the Dart enums, and defaulting it would ship a catalogue that is quietly
/// wrong rather than loudly broken.
abstract final class ExerciseJson {
  static Exercise fromMap(Map<String, dynamic> data) {
    final id = data['id'];
    if (id is! String || id.isEmpty) {
      throw CatalogFailure(CatalogFailureKind.assetMalformed, detail: 'record with no id: $data');
    }

    final name = data['name'];
    if (name is! String || name.isEmpty) {
      throw CatalogFailure(CatalogFailureKind.assetMalformed, detail: 'exercise $id has no name');
    }

    return Exercise(
      id: id,
      name: name,
      aliases: _strings(data['aliases']),
      bodyPart: _require(BodyPart.tryFromWire(data['bodyPart']), id, 'bodyPart', data['bodyPart']),
      primaryMuscle: _require(
        Muscle.tryFromWire(data['primaryMuscle']),
        id,
        'primaryMuscle',
        data['primaryMuscle'],
      ),
      // The only optional enum: a record without a synergist is legitimate,
      // a record with an unrecognised one is not.
      synergist: data['synergist'] == null
          ? null
          : _require(Muscle.tryFromWire(data['synergist']), id, 'synergist', data['synergist']),
      secondaryMuscles: [
        for (final muscle in _strings(data['secondaryMuscles']))
          _require(Muscle.tryFromWire(muscle), id, 'secondaryMuscles', muscle),
      ],
      equipment: _require(
        Equipment.tryFromWire(data['equipment']),
        id,
        'equipment',
        data['equipment'],
      ),
      loadModel: _require(
        LoadModel.tryFromWire(data['loadModel']),
        id,
        'loadModel',
        data['loadModel'],
      ),
      steps: _strings(data['steps']),
      // Stored relative to the pinned upstream commit; absolute from here on.
      thumbnailUrl: CatalogConfig.mediaUrl(data['thumbnailUrl'] as String?),
      gifUrl: CatalogConfig.mediaUrl(data['gifUrl'] as String?),
      attribution: data['attribution'] as String?,
      source: ExerciseSource.catalogue,
    );
  }

  static T _require<T>(T? value, String id, String field, Object? raw) {
    if (value != null) return value;
    throw CatalogFailure(
      CatalogFailureKind.unknownValue,
      detail: 'exercise $id: $field is ${raw == null ? 'missing' : '"$raw"'}, '
          'which this build has no $T for',
    );
  }

  static List<String> _strings(Object? value) {
    if (value is! List) return const [];
    return [
      for (final item in value)
        if (item is String) item,
    ];
  }
}
